### ISSUE TITLE
make_data.py TypeError

### ISSUE THREAD

**Issue by QazCetelic** [desertkun/brainout#16]
```
/usr/bin/python2 /home/qaz/Programming/Java/brainout/scripts/make_data.py
Warning: no private key, making data without signing!
Building for platform client
Executing script 'Copy binaries'...
Executing script 'Prebuild packages'...
Copying package 'base' for platform 'client'
Processing smart package '../data/packages/base/smart'
Traceback (most recent call last):
  File "/home/qaz/Programming/Java/brainout/scripts/make_data.py", line 35, in <module>
    config.make_data(platform)
  File "/home/qaz/Programming/Java/brainout/scripts/config.py", line 40, in make_data
    script.call(platform)
  File "/home/qaz/Programming/Java/brainout/scripts/config.py", line 27, in call
    self.method(self.src, self.dst, platform)
  File "/home/qaz/Programming/Java/brainout/scripts/scripts.py", line 143, in prebuild_packages
    process_smart(path, contents, platform_filter_rules)
  File "/home/qaz/Programming/Java/brainout/scripts/scripts.py", line 449, in process_smart
    pieces = [process_piece(file, piece) for piece in text.split(u"--------")]
  File "/home/qaz/Programming/Java/brainout/scripts/scripts.py", line 436, in process_piece
    return hjson.loads(text, cls=CustomHjsonDecoder)
  File "/usr/lib/python2.7/site-packages/hjson/__init__.py", line 188, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/home/qaz/Programming/Java/brainout/scripts/scripts.py", line 339, in __init__
    super(CustomHjsonDecoder, self).__init__(*args, tfnns_hook=self._parse_tfnns, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'tfnns_hook'

Process finished with exit code 1
```

**Comment by desertkun** [comment]
You need custom modified hjson, regular won't do. See dependencies section of the readme.

**Comment by QazCetelic** [comment]
I did install the custom hjson, but it seems like the normal (system-wide) package was used.
I removed it and now it works fine.
